version: '3.8'

services:
  production:
    container_name: nodejs-api-production
    build:
      context: .
      target: production
      args:
        REDIS_HOST: localhost
        REDIS_PORT: 6370
        POSTGRES_HOST: localhost
        POSTGRES_DB: example-app-database-production
        POSTGRES_USER: example-app-user-production
        POSTGRES_PASSWORD: example-app-password
        POSTGRES_PORT: 5432
    ports:
      - '3001:3000'
    restart: unless-stopped

  develop:
    container_name: nodejs-api-dev
    build:
      context: .
      target: production
      args:
        REDIS_HOST: redis-container-develop
        REDIS_PORT: 6372
        POSTGRES_HOST: postgres-container
        POSTGRES_DB: example-app-database-develop
        POSTGRES_USER: example-app-user-develop
        POSTGRES_PASSWORD: example-app-password
        POSTGRES_PORT: 5432
    ports:
      - '3002:3000'
    restart: unless-stopped

  staging:
    container_name: nodejs-api-staging
    build:
      context: .
      target: production
      args:
        REDIS_HOST: redis-container-staging
        REDIS_PORT: 6371
        POSTGRES_HOST: postgres-container
        POSTGRES_DB: example-app-database-staging
        POSTGRES_USER: example-app-user-staging
        POSTGRES_PASSWORD: example-app-password
        POSTGRES_PORT: 5432
    ports:
      - '3003:3000'
    restart: unless-stopped