name: Deployment

on:
  push:
    branches:
      - master
      - staging
      - develop

env:
  BUILD_ENVIRONMENT: ${{
    github.ref_name == 'master' && 'production' ||
    github.ref_name == 'staging' && 'staging' ||
    github.ref_name == 'develop' && 'develop'
    }}

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short commit hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push with commit hash tag
        run: |
          ddocker build --target production -t example-app-image .
          docker image ls
          docker tag example-app-image mdtazbinur/example-app:${{ steps.vars.outputs.sha_short }}
          docker push mdtazbinur/example-app:${{ steps.vars.outputs.sha_short }}

  deploy-image:
    needs: build-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Print sha_short value
        run: echo "sha_short=${{ needs.build-push-image.outputs.sha_short }}"

      - name: Print BUILD_ENVIRONMENT value
        run: echo "env.BUILD_ENVIRONMENT=${{ env.BUILD_ENVIRONMENT }}"

      - name: Deploy to AWS-EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER_NAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Log in to Docker Hub using the access token
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            cd example-app-server
            pwd

            if [ "${{ env.BUILD_ENVIRONMENT }}" == "production" ]; then
              sed -i "s/^PRODUCTION_APP_IMAGE_TAG=[^ ]*/PRODUCTION_APP_IMAGE_TAG=${{ needs.build-push-image.outputs.sha_short }}/" .env
            elif [ "${{ env.BUILD_ENVIRONMENT }}" == "staging" ]; then
              sed -i "s/^STAGING_APP_IMAGE_TAG=[^ ]*/STAGING_APP_IMAGE_TAG=${{ needs.build-push-image.outputs.sha_short }}/" .env
            elif [ "${{ env.BUILD_ENVIRONMENT }}" == "develop" ]; then
              sed -i "s/^DEVELOP_APP_IMAGE_TAG=[^ ]*/DEVELOP_APP_IMAGE_TAG=${{ needs.build-push-image.outputs.sha_short }}/" .env
            fi

            container_name="example-app-api-${{ env.BUILD_ENVIRONMENT }}"

            # Stop running container
            if [ "$(docker ps -f name=$container_name -q)" ]; then
              docker stop $container_name
            fi

            # Get the image of the stopped container
            old_image=$(docker ps -a -f name=$container_name --format "{{.Image}}")

            # Remove stopped container
            if [ "$(docker ps -a -f name=$container_name -q)" ]; then
              docker rm $container_name
            fi

            # Remove old image if it exists
            if [ -n "$old_image" ]; then
              docker rmi $old_image
            fi

            # Pull new image & run container
            docker-compose up ${{ env.BUILD_ENVIRONMENT }} --build -d

            # Logout docker
            docker logout
